version: "3.3"

services:
  message_queue:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"

  server:
    image: elderlypassionfruit/soa2-env
    ports:
      - 50051:50051/tcp

    environment:
      GAME_SIZE: 4

    command: python3 start_server.py
    depends_on:
      - message_queue

  bot:
    image: elderlypassionfruit/soa2-env

    environment:
      IS_BOT: 1

    scale: 3

    command: python3 start_client.py
    depends_on:
      - server
    restart: always
