# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftest_data.proto\"\xa2\x01\n\x08TestData\x12\x0b\n\x03int\x18\x01 \x01(\x05\x12\r\n\x05\x66loat\x18\x02 \x01(\x02\x12\x0e\n\x06string\x18\x03 \x01(\t\x12\x0c\n\x04\x62ool\x18\x04 \x01(\x08\x12!\n\x04\x64ict\x18\x05 \x03(\x0b\x32\x13.TestData.DictEntry\x12\x0c\n\x04list\x18\x06 \x03(\t\x1a+\n\tDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')



_TESTDATA = DESCRIPTOR.message_types_by_name['TestData']
_TESTDATA_DICTENTRY = _TESTDATA.nested_types_by_name['DictEntry']
TestData = _reflection.GeneratedProtocolMessageType('TestData', (_message.Message,), {

  'DictEntry' : _reflection.GeneratedProtocolMessageType('DictEntry', (_message.Message,), {
    'DESCRIPTOR' : _TESTDATA_DICTENTRY,
    '__module__' : 'test_data_pb2'
    # @@protoc_insertion_point(class_scope:TestData.DictEntry)
    })
  ,
  'DESCRIPTOR' : _TESTDATA,
  '__module__' : 'test_data_pb2'
  # @@protoc_insertion_point(class_scope:TestData)
  })
_sym_db.RegisterMessage(TestData)
_sym_db.RegisterMessage(TestData.DictEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTDATA_DICTENTRY._options = None
  _TESTDATA_DICTENTRY._serialized_options = b'8\001'
  _TESTDATA._serialized_start=20
  _TESTDATA._serialized_end=182
  _TESTDATA_DICTENTRY._serialized_start=139
  _TESTDATA_DICTENTRY._serialized_end=182
# @@protoc_insertion_point(module_scope)
