# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mafia.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmafia.proto\"!\n\x10SubscribeRequest\x12\r\n\x05login\x18\x01 \x01(\t\"\x81\x02\n\x11SubscribeResponse\x12%\n\x03\x61\x63k\x18\x01 \x01(\x0b\x32\x16.SubscribeResponse.AckH\x00\x12\x32\n\nnew_player\x18\x02 \x01(\x0b\x32\x1c.SubscribeResponse.NewPlayerH\x00\x12)\n\x05start\x18\x03 \x01(\x0b\x32\x18.SubscribeResponse.StartH\x00\x1a\x16\n\x03\x41\x63k\x12\x0f\n\x07game_id\x18\x01 \x01(\x03\x1a\x1a\n\tNewPlayer\x12\r\n\x05login\x18\x01 \x01(\t\x1a&\n\x05Start\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07players\x18\x02 \x03(\tB\n\n\x08response\"=\n\x04Vote\x12\x0f\n\x07game_id\x18\x01 \x01(\x03\x12\x12\n\nlogin_from\x18\x02 \x01(\t\x12\x10\n\x08login_to\x18\x03 \x01(\t\"\t\n\x07Nothing\"+\n\tFinishDay\x12\x0f\n\x07game_id\x18\x01 \x01(\x03\x12\r\n\x05login\x18\x02 \x01(\t\"9\n\x11\x46inishDayResponse\x12\x14\n\x0ckilled_login\x18\x01 \x01(\t\x12\x0e\n\x06winner\x18\x02 \x01(\x05\"-\n\x0bWaitNextDay\x12\x0f\n\x07game_id\x18\x01 \x01(\x03\x12\r\n\x05login\x18\x02 \x01(\t\"_\n\x13WaitNextDayResponse\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\x03\x12\x15\n\ralive_players\x18\x02 \x03(\t\x12\x14\n\x0ckilled_login\x18\x03 \x01(\t\x12\x0e\n\x06winner\x18\x04 \x01(\x05\"\'\n\x05\x43heck\x12\x0f\n\x07game_id\x18\x01 \x01(\x03\x12\r\n\x05login\x18\x02 \x01(\t\"\x1d\n\rCheckResponse\x12\x0c\n\x04role\x18\x01 \x01(\t*:\n\x15SubscribeResponseType\x12\x07\n\x03\x41\x63k\x10\x00\x12\r\n\tNewPlayer\x10\x01\x12\t\n\x05Start\x10\x02\x32\x88\x02\n\x0bMafiaServer\x12\x34\n\tSubscribe\x12\x11.SubscribeRequest\x1a\x12.SubscribeResponse0\x01\x12\x19\n\x06\x44oVote\x12\x05.Vote\x1a\x08.Nothing\x12-\n\x0b\x44oFinishDay\x12\n.FinishDay\x1a\x12.FinishDayResponse\x12\x33\n\rDoWaitNextDay\x12\x0c.WaitNextDay\x1a\x14.WaitNextDayResponse\x12\x1e\n\x0b\x44oMafiaVote\x12\x05.Vote\x1a\x08.Nothing\x12$\n\nDoCopCheck\x12\x06.Check\x1a\x0e.CheckResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mafia_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUBSCRIBERESPONSETYPE._serialized_start=704
  _SUBSCRIBERESPONSETYPE._serialized_end=762
  _SUBSCRIBEREQUEST._serialized_start=15
  _SUBSCRIBEREQUEST._serialized_end=48
  _SUBSCRIBERESPONSE._serialized_start=51
  _SUBSCRIBERESPONSE._serialized_end=308
  _SUBSCRIBERESPONSE_ACK._serialized_start=206
  _SUBSCRIBERESPONSE_ACK._serialized_end=228
  _SUBSCRIBERESPONSE_NEWPLAYER._serialized_start=230
  _SUBSCRIBERESPONSE_NEWPLAYER._serialized_end=256
  _SUBSCRIBERESPONSE_START._serialized_start=258
  _SUBSCRIBERESPONSE_START._serialized_end=296
  _VOTE._serialized_start=310
  _VOTE._serialized_end=371
  _NOTHING._serialized_start=373
  _NOTHING._serialized_end=382
  _FINISHDAY._serialized_start=384
  _FINISHDAY._serialized_end=427
  _FINISHDAYRESPONSE._serialized_start=429
  _FINISHDAYRESPONSE._serialized_end=486
  _WAITNEXTDAY._serialized_start=488
  _WAITNEXTDAY._serialized_end=533
  _WAITNEXTDAYRESPONSE._serialized_start=535
  _WAITNEXTDAYRESPONSE._serialized_end=630
  _CHECK._serialized_start=632
  _CHECK._serialized_end=671
  _CHECKRESPONSE._serialized_start=673
  _CHECKRESPONSE._serialized_end=702
  _MAFIASERVER._serialized_start=765
  _MAFIASERVER._serialized_end=1029
# @@protoc_insertion_point(module_scope)
